### ISSUE TITLE
new check: has_role

### ISSUE THREAD

**Issue by sami0596** [Catalyst4222/interactions-checks#2]
Discord.py had `has_role('the_role')` 
Possible to add that too?

**Comment by Catalyst4222** [comment]
I've made a check for it as of [8e9b5bf](https://github.com/Catalyst4222/interactions-checks/commit/8e9b5bf624eaf64b60322b73eb10bfea02f31d3d). If you need to use it immediately, you can install from github, or you can wait until I test it more and publish it to pip

Apologies for the long wait, I've been busy with work on the main lib and life in general
